import { sql } from "drizzle-orm";
import { timestamp, uuid } from "drizzle-orm/pg-core";

/** Primary key: random UUID generated by Postgres. */
export const id = () => uuid().primaryKey().default(sql`gen_random_uuid()`);

export const createdAt = () =>
  timestamp({ withTimezone: true, mode: "date" }).notNull().defaultNow();

export const updatedAt = () =>
  timestamp({ withTimezone: true, mode: "date" })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

export const tsz = () => timestamp({ withTimezone: true, mode: "date" });
