/**
 * Authentication tables. Shape follows Better Auth's Drizzle schema
 * (user / session / account / verification) so the auth library can be plugged in
 * during Phase 3 without a schema rewrite. IDs are UUIDs generated by Postgres.
 */
import { boolean, index, pgTable, text, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createdAt, id, tsz, updatedAt } from "./_shared";

export const user = pgTable(
  "user",
  {
    id: id(),
    name: text().notNull(),
    email: text().notNull(),
    emailVerified: boolean().notNull().default(false),
    image: text(),
    /** Interface language ("en" | "de"); null = follow the browser. */
    locale: text(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("user_email_lower_uq").on(sql`lower(${t.email})`)],
);

export const session = pgTable(
  "session",
  {
    id: id(),
    userId: uuid()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    token: text().notNull().unique(),
    expiresAt: tsz().notNull(),
    ipAddress: text(),
    userAgent: text(),
    /** Workspace the user is currently working in. */
    activeWorkspaceId: uuid(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index().on(t.userId)],
);

export const account = pgTable(
  "account",
  {
    id: id(),
    userId: uuid()
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accountId: text().notNull(),
    providerId: text().notNull(),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: tsz(),
    refreshTokenExpiresAt: tsz(),
    scope: text(),
    /** Password hash for the email/password provider. Never plaintext. */
    password: text(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index().on(t.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: id(),
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: tsz().notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index().on(t.identifier)],
);
